sonata_repo: facebook/sonata
finetune_strategy: two_stage
decoder_dims:
- 512
- 256
- 128
- 64
num_cp_bins: 256
bin_centers: null
upcast_dim: 1088
num_concat_levels: 2
use_geometric_features: true
learning_rate: 0.0001
weight_decay: 0.01
lr_decay_rate: 0.65
unfreeze_from_stage: 3
warmup_frozen_epochs: 10
max_epochs: 100
dropout: 0.1
data_dir: /mnt/storage01/workspace/research/zephyr/02_processed/DrivAerNet/140b9b2dc4e57ccc4e6856fdc1a116126b724ba2522232f88131827edc9e602e
batch_size: 1
num_workers: 4
h5_filename: mesh.h5
train_list_file: train_design_ids.txt
test_list_file: test_design_ids.txt
normalize: true
grid_size: 0.02
batching_enabled: true
use_cp_binning: true
recompute_stats: false
