sonata_repo: facebook/sonata
freeze_encoder: true
decoder_dims:
- 512
- 256
- 128
- 64
num_cp_bins: 64
emd_l1_weight: 0.5
bin_centers: null
sonata_dim: 512
learning_rate: 0.0001
weight_decay: 0.01
warmup_epochs: 5
max_epochs: 100
dropout: 0.1
data_dir: /mnt/storage01/workspace/research/zephyr/02_processed/DrivAerNet/140b9b2dc4e57ccc4e6856fdc1a116126b724ba2522232f88131827edc9e602e
batch_size: 8
num_workers: 32
h5_filename: mesh.h5
train_list_file: train_design_ids.txt
test_list_file: test_design_ids.txt
normalize: true
grid_size: 0.02
batching_enabled: true
use_cp_binning: true
