sonata_repo: facebook/sonata
freeze_sonata: true
sonata_dim: 512
hidden_dim: 128
num_layers: 8
num_heads: 8
slice_num: 32
mlp_ratio: 4
dropout: 0.1
num_cp_bins: 64
emd_l1_weight: 0.5
bin_centers: null
learning_rate: 0.001
weight_decay: 0.0001
warmup_steps: 1
max_steps: 100000
cache_dir: ./data/sonata_cache
enable_caching: false
data_dir: /mnt/storage01/workspace/research/zephyr/02_processed/DrivAerNet/140b9b2dc4e57ccc4e6856fdc1a116126b724ba2522232f88131827edc9e602e
batch_size: 1
num_workers: 32
h5_filename: mesh.h5
train_list_file: train_design_ids.txt
test_list_file: test_design_ids.txt
normalize: true
grid_size: 0.02
batching_enabled: false
use_cp_binning: true
